//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPorjectDatabaseFirst3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
        [DisplayName("Booking Number")]
        public int BookingId { get; set; }
        [DisplayName("Customer Name")]
        public string CustomerName { get; set; }
        [DisplayName("Mobile Number")]
        [DataType(DataType.PhoneNumber)]
        public string CustomerMobile { get; set; }
        [DisplayName("Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> BookedDate { get; set; }
        [DisplayName("Status")]
        public string BookedStatus { get; set; }
        [DisplayName("Ticket Price")]
        public Nullable<decimal> Price { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> CancelDate { get; set; }
        [DisplayName("Return Amount")]
        public Nullable<decimal> ReturnAmount { get; set; }
        [DisplayName("Return Status")]
        public Nullable<int> ReturnStatus { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
