//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPorjectDatabaseFirst3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BookingDetail
    {
        [DisplayName("Booking Details Number")]
        public int BookingDetailsId { get; set; }
        [DisplayName("Seat Number")]
        public string SeatNo { get; set; }
        [DisplayName("Customer Name")]
        public string CustomerName { get; set; }
        [DisplayName("Mobile Number")]
        [Required(ErrorMessage ="Number should be valid")]
        [DataType(DataType.PhoneNumber)]
        public string CustomerMobile { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> ScheduleDetailsId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Bus Bus { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ScheduleDetail ScheduleDetail { get; set; }
    }
}
