//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPorjectDatabaseFirst3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.Routes = new HashSet<Route>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
        }
    
        public int BusId { get; set; }
        [DisplayName("Bus Name")]
        public string BusName { get; set; }
        [DisplayName("Bus Type")]
        public string BusType { get; set; }
        [DisplayName("Number of Seat")]
        public Nullable<int> NoOfSeat { get; set; }
        [DisplayName("License No. ")]
        public string LicenseNo { get; set; }
        [DisplayName("Fitness Status")]
        public Nullable<bool> FitnessStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}
